influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  env_file:
    - 'env.influxdb'
  volumes:
    - /mnt/fastraid/influxdb:/var/lib/influxdb

telegraf:
  image: telegraf:latest
  container_name: telegraf
  ports: 
    - "8125:8125/udp"
  links:
    - influxdb
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro

grafana:
  image: grafana/grafana:6.1.0-beta1
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  links:
    - influxdb
  volumes:
    - /mnt/fastraid/grafana:/var/lib/grafana
